export const STATUS = {
  ISSUE_REQUEST_SENT: 'Issue Request Sent',
  MATERIAL_REQUEST_SENT: 'Material Request Sent',
  PURCHASE_REQUEST_SENT: 'Purchase Request Sent',
  CHECKOUT: 'Checkout',
  CREATING_PURCHASE_ORDER: 'Creating Purchase Order',
  PURCHASE_ORDER_SENT: 'Purchase Order Sent',
  DELIVERY: 'Delivery',
  DELIVERED: 'Delivered',
  ISSUE_GOOD_SENT: 'Issue Good Sent',
  CANCELLED: 'Cancelled',
  SELECTED_FOR_CHECKOUT: 'Selected for Checkout',
  BOOK_REQUEST: 'Book Request',
  DECLINED: 'Declined',
  BOOK_CANCELLED: 'Booked Cancelled',
};
